name:                postlude
version:             0.1.0.4
github:              "jrpotter/postlude"
license:             BSD3
author:              "Joshua Potter"
maintainer:          "jrpotter2112@gmail.com"
copyright:           "2018 Joshua Potter"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at
                     <https://github.com/jrpotter/postlude#readme>

dependencies:
  - base >=4.7 && <5
  - bytestring >=0.10.8.1 && <0.11
  - exceptions >=0.6 && <0.9
  - free >=4.12 && < 5
  - mtl >=2.2.1 && <2.3
  - text >=1.2.2.2 && <1.3
  - transformers >=0.4 && <0.6

library:
  source-dirs: src
